{
  "openapi": "3.0.0",
  "info": {
    "title": "Platform Management",
    "description": "",
    "contact": {},
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.vcita.biz/v3/"
    }
  ],
  "tags": [
    {
      "name": "subscriptionsmng",
      "description": ""
    }
  ],
  "paths": {
    "/subscriptions": {
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "List all Subscriptions",
        "description": "List all subscriptions in scope.\n\nAvailable only for **Directory Tokens**           \n",
        "parameters": [
          {
            "name": "page",
            "in": "query",
            "description": "Page number of the results.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "default": 1
            }
          },
          {
            "name": "per_page",
            "in": "query",
            "description": "How many items to return per page.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "maximum": 100,
              "type": "integer",
              "default": 25
            }
          },
          {
            "name": "sort",
            "in": "query",
            "description": "Sort by fields, e.g., \"created_at:asc,updated_at:desc\".",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "default": "updated_at:desc"
            }
          },
          {
            "name": "filter",
            "in": "query",
            "description": "Use LHS barckets to filter\n\nSupported fields: **created_at, updated_at**\n",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            },
            "example": "filter[created][lte]=2020-01-01&filter[created][gte]=2019-01-01&filter[name][contains]=joh"
          }
        ],
        "responses": {
          "200": {
            "description": "A list of subscriptions.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": [
          "Directory",
          "Business"
        ]
      },
      "post": {
        "tags": [
          "Subscription"
        ],
        "summary": "Create a Subscription",
        "description": "Create a new subscription for a business.\n\n**Available only for Directory token**\n",
        "operationId": "create",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/subscription"
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_201"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Directory"
      }
    },
    "/subscriptions/{subscription_uid}": {
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "Retrieve a Subscription",
        "description": "Update a subscription\n\n**Available only for Directory token.**\n",
        "operationId": "read",
        "parameters": [
          {
            "name": "subscription_uid",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Subscription Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_1"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Directory"
      },
      "put": {
        "tags": [
          "Subscription"
        ],
        "summary": "Update a Subscription",
        "description": "Update a subscription\n\n**Available only for Directory token.**\n",
        "operationId": "update",
        "parameters": [
          {
            "name": "subscription_uid",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/subscription"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_2"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Directory"
      },
      "delete": {
        "tags": [
          "Subscription"
        ],
        "summary": "Delete (Cancel) a Subscription",
        "description": "Delete (Cancel) a subscription\n\n**Available only for Directory token.**\n",
        "operationId": "delete",
        "parameters": [
          {
            "name": "subscription_uid",
            "in": "path",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Directory"
      }
    },
    "/businesses": {
      "get": {
        "tags": [
          "Business"
        ],
        "summary": "List All Business Accounts",
        "description": "Retrieves a list of Business Accounts based on the filter parameters supplied and the token access scope. A directory will see all it's business accounts, an application will see its subscribed businesses\n   \nAvailable for only for  **Directory Tokens**\n",
        "parameters": [
          {
            "name": "directory_uid",
            "in": "query",
            "description": "directory uid",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "business_uid",
            "in": "query",
            "description": "business account unique identifier",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "external_refrence_id",
            "in": "query",
            "description": "external refernece id",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "email",
            "in": "query",
            "description": "the business owner email address",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A List of businesses",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/inline_response_200_3"
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "post": {
        "tags": [
          "Business"
        ],
        "summary": "Create a Business Account",
        "description": "Create a new Business Account.\n\nAvailable only for **Directory tokens**\n",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/businesses_body"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Business Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_4"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Application, Business, Directory"
      }
    },
    "/businesses/{business_id}": {
      "get": {
        "tags": [
          "Business"
        ],
        "summary": "Retrieve a Business Account",
        "description": "Retrieves a Business Account object based on its ID. \n\nAvailable ony for **Directory tokens**\n",
        "parameters": [
          {
            "name": "business_id",
            "in": "path",
            "description": "Business ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Business Retrieved",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_5"
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ],
        "x-auth-type": "Application, Directory"
      },
      "put": {
        "tags": [
          "Business"
        ],
        "summary": "Update a Business Account",
        "description": "Update a Business Account object.\n\nAvailable ony for **Directory tokens**\n",
        "parameters": [
          {
            "name": "business_id",
            "in": "path",
            "description": "Business ID",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/business"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Business Updated",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/inline_response_200_5"
                }
              }
            }
          },
          "400": {
            "description": "Business Updated",
            "content": {
              "application/json": {
                "examples": {
                  "response": {
                    "value": {
                      "message": "Incorrect parameters for update",
                      "status": "Error"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      },
      "delete": {
        "tags": [
          "Business"
        ],
        "summary": "Deletes a Business Account",
        "description": "Deletes the Business Account with the specified ID. \n\nAvailable ony for **Directory tokens**\n",
        "parameters": [
          {
            "name": "business_id",
            "in": "path",
            "description": "The ID of the business to delete.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successfully deleted"
          },
          "404": {
            "description": "Not Found - The business could not be found"
          }
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Staff": {
        "required": [
          "email",
          "first_name",
          "last_name",
          "staff_id"
        ],
        "type": "object",
        "properties": {
          "active": {
            "type": "string",
            "description": "Indicates whether the staff member is active. Expected values are 'true' or 'false'."
          },
          "deleted": {
            "type": "string",
            "description": "Indicates whether the staff member has been deleted. Expected values are 'true' or 'false'."
          },
          "display_name": {
            "type": "string",
            "description": "The staff member's display name, typically a combination of first and last name."
          },
          "email": {
            "type": "string",
            "description": "The staff member's email address.",
            "format": "email"
          },
          "first_name": {
            "type": "string",
            "description": "The staff member's first name."
          },
          "staff_id": {
            "type": "string",
            "description": "A unique identifier for the staff member."
          },
          "invite_sent": {
            "type": "string",
            "description": "Timestamp of when an invite was sent to the staff member, in YYYY-MM-DD HH:MM:SS format."
          },
          "last_name": {
            "type": "string",
            "description": "The staff member's last name."
          },
          "mobile_number": {
            "type": "string",
            "description": "The staff member's mobile phone number."
          },
          "photo": {
            "type": "string",
            "description": "A URL to the staff member's photo. Null if no photo is available.",
            "nullable": true
          },
          "photo_path": {
            "type": "string",
            "description": "The path to the staff member's photo. Empty if no photo is available."
          },
          "professional_title": {
            "type": "string",
            "description": "The staff member's professional title."
          },
          "role": {
            "type": "string",
            "description": "The role of the staff member within the organization (e.g., admin)."
          }
        },
        "example": {
          "active": "true",
          "deleted": "false",
          "display_name": "FName LName 1",
          "email": "staff_1@email.com",
          "first_name": "FName",
          "staff_id": "1a123b456c789d",
          "invite_sent": "2015-10-23 13:02:09",
          "last_name": "LName 1",
          "mobile_number": "0500000000",
          "photo_path": "",
          "professional_title": "Staff Title 1",
          "role": "admin"
        }
      },
      "subscription": {
        "required": [
          "bundled_from_subscription_uid",
          "business_uid",
          "buyer_uid",
          "cancellation_date",
          "created_at",
          "display_name",
          "expiration_date",
          "is_active",
          "pay_per_unit",
          "payment_type",
          "purchasable_uid",
          "purchase_currency",
          "purchase_price",
          "purchase_state",
          "subscription_uid",
          "updated_at"
        ],
        "type": "object",
        "properties": {
          "is_active": {
            "type": "boolean",
            "description": "Active subscription is when the subscription is not canceled and not expired."
          },
          "subscription_uid": {
            "type": "string",
            "description": "The entity uid.",
            "x-security": [
              "Business"
            ]
          },
          "display_name": {
            "type": "string",
            "description": "The subscription display name."
          },
          "updated_at": {
            "type": "string",
            "description": "The last updated date and time of the object.",
            "format": "date-time"
          },
          "created_at": {
            "type": "string",
            "description": "The creation date and time of the object.",
            "format": "date-time"
          },
          "purchasable_uid": {
            "type": "string",
            "description": "The item purchased uid."
          },
          "purchase_state": {
            "type": "string",
            "description": "The current subscription state."
          },
          "cancellation_date": {
            "type": "string",
            "description": "The date when subscription was canceled.",
            "format": "date-time"
          },
          "expiration_date": {
            "type": "string",
            "description": "The date when subscription was expired.",
            "format": "date-time"
          },
          "buyer_uid": {
            "type": "string",
            "description": "The actor of the action, the staff uid."
          },
          "business_uid": {
            "type": "string",
            "description": "The business that the subscription relates to."
          },
          "purchase_price": {
            "type": "number",
            "description": "The purchase price at the moment of the subscription was created."
          },
          "purchase_currency": {
            "type": "string",
            "description": "The purchase currency at the moment of the subscription was created."
          },
          "payment_type": {
            "type": "string",
            "description": "The pay_per_unit attributes purchased on the subscription."
          },
          "pay_per_unit": {
            "type": "array",
            "description": "The pay_per_unit attributes purchased on the subscription.",
            "items": {
              "type": "string"
            }
          },
          "bundled_from_subscription_uid": {
            "type": "string",
            "description": "The subscription uid that this subscription is bundled from."
          }
        },
        "example": {
          "is_active": true,
          "subscription_uid": "sub_123456789",
          "display_name": "Premium Subscription",
          "updated_at": "2024-03-20T12:34:56Z",
          "created_at": "2024-01-01T09:00:00Z",
          "purchasable_uid": "item_987654321",
          "purchase_state": "active",
          "expiration_date": "2025-01-01T00:00:00Z",
          "buyer_uid": "user_12345",
          "business_uid": "biz_67890",
          "purchase_price": 99.99,
          "purchase_currency": "USD",
          "payment_type": "monthly",
          "pay_per_unit": [
            "basic",
            "premium"
          ]
        }
      },
      "business": {
        "required": [
          "business_uid",
          "name"
        ],
        "type": "object",
        "properties": {
          "account_blocked_at": {
            "type": "string",
            "description": "The date and time when the business account was blocked, in ISO 8601 format.",
            "format": "date-time"
          },
          "address": {
            "type": "string",
            "description": "The physical address of the business."
          },
          "business_category": {
            "type": "string",
            "description": "The category that best describes the business sector."
          },
          "business_maturity_in_years": {
            "type": "string",
            "description": "The number of years the business has been operational, represented as a string."
          },
          "country_name": {
            "type": "string",
            "description": "The name of the country where the business is located."
          },
          "hide_Address": {
            "type": "boolean",
            "description": "A boolean indicating whether the business address should be hidden in public listings."
          },
          "business_uid": {
            "type": "string",
            "description": "The unique identifier for the business."
          },
          "landing_page": {
            "type": "string",
            "description": "The URL of the business's landing page."
          },
          "name": {
            "type": "string",
            "description": "The name of the business."
          },
          "phone": {
            "type": "string",
            "description": "The contact phone number for the business."
          },
          "promotional": {
            "$ref": "#/components/schemas/businessPromotional"
          },
          "short_description": {
            "type": "string",
            "description": "A brief description of the business."
          },
          "time_zone": {
            "type": "string",
            "description": "The time zone in which the business operates."
          },
          "website_url": {
            "type": "string",
            "description": "The URL of the business's website."
          }
        },
        "example": {
          "account_blocked_at": "2023-04-15T09:10:11Z",
          "address": "123 Business St, Business City, BC 12345",
          "business_category": "Retail",
          "business_maturity_in_years": "5",
          "country_name": "United States",
          "hide_Address": false,
          "business_uid": "business-12345",
          "landing_page": "http://www.businesswebsite.com",
          "name": "Business Name Inc.",
          "phone": "+1234567890",
          "promotional": {
            "block_count": "2",
            "blocked_at": "2023-01-10T09:10:11Z"
          },
          "short_description": "A leading provider of business services.",
          "time_zone": "America/New_York",
          "website_url": "http://www.businesswebsite.com"
        }
      },
      "businessPromotional": {
        "type": "object",
        "properties": {
          "block_count": {
            "type": "string",
            "description": "The number of times promotional content related to the business has been blocked, represented as a string."
          },
          "blocked_at": {
            "type": "string",
            "description": "The date and time when the business's promotional content was last blocked, in ISO 8601 format.",
            "format": "date-time"
          }
        },
        "description": "Information related to the blocking of promotional content for the business."
      },
      "businessMeta": {
        "required": [
          "external_id",
          "external_reference_id",
          "in_setup",
          "is_template"
        ],
        "type": "object",
        "properties": {
          "analytics": {
            "$ref": "#/components/schemas/businessAnalytics"
          },
          "audit": {
            "type": "array",
            "description": "A collection of audit logs for tracking changes or activities. The specific structure of each log is not defined.",
            "items": {
              "type": "object"
            }
          },
          "external_id": {
            "type": "string",
            "description": "A unique identifier for the business used in external systems. (deperecated, use external_reference_id)"
          },
          "external_reference_id": {
            "type": "string",
            "description": "Another identifier used for referencing the business in external or third-party systems."
          },
          "identities": {
            "type": "array",
            "description": "A list of identities associated with the business. This could include various user or entity IDs.",
            "items": {
              "type": "string"
            }
          },
          "in_setup": {
            "type": "boolean",
            "description": "Indicates whether the business is in the setup process. True if in setup, false otherwise."
          },
          "intents": {
            "type": "array",
            "description": "A list of intents or purposes associated with the business. Defines business objectives or goals.",
            "items": {
              "type": "string"
            }
          },
          "invite": {
            "type": "string",
            "description": "An invite code or identifier used for inviting users to the business or a specific function."
          },
          "is_template": {
            "type": "boolean",
            "description": "Indicates if the current business meta is a template. Templates can be used as a basis for new instances."
          },
          "note": {
            "type": "string",
            "description": "A general note or comment about the business. Can be used for additional information not captured elsewhere."
          },
          "suggested_identities": {
            "type": "array",
            "description": "A list of suggested identities for the business, possibly recommended during setup or integration.",
            "items": {
              "type": "string"
            }
          },
          "tags": {
            "type": "array",
            "description": "Tags associated with the business for categorization or organization purposes.",
            "items": {
              "type": "string"
            }
          },
          "template_business_id": {
            "type": "string",
            "description": "If this business meta is based on a template, this is the ID of that template business."
          }
        },
        "description": "The BusinessMeta schema defines various metadata properties associated with a business entity, including analytics, identity information, state indicators, and categorization tags.",
        "example": {
          "analytics": {
            "google_client_id": "GA-12345678",
            "mixpanel_id": "mixpanel-12345"
          },
          "audit": [],
          "external_id": "ext-987654321",
          "external_reference_id": "extref-123456789",
          "identities": [
            "user-1234",
            "user-5678"
          ],
          "in_setup": false,
          "intents": [
            "increase-sales",
            "expand-market"
          ],
          "invite": "inviteCode12345",
          "is_template": false,
          "note": "This is a sample business meta for demonstration.",
          "suggested_identities": [
            "suggested-user-123",
            "suggested-user-456"
          ],
          "tags": [
            "retail",
            "online",
            "B2C"
          ],
          "template_business_id": ""
        }
      },
      "businessAnalytics": {
        "type": "object",
        "properties": {
          "google_client_id": {
            "type": "string",
            "description": "A unique identifier for the business within Google's analytics platform. Used for tracking and analyzing user interactions with the business's digital assets."
          },
          "mixpanel_id": {
            "type": "string",
            "description": "A unique identifier for the business within Mixpanel's analytics platform. Enables detailed analysis of user behavior and interactions across the business's digital interfaces."
          }
        },
        "example": {
          "google_client_id": "UA-12345678-9",
          "mixpanel_id": "98ef76a4c5f12345b6789d12"
        }
      },
      "inline_response_200": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean",
            "example": true
          },
          "data": {
            "$ref": "#/components/schemas/inline_response_200_data"
          },
          "page": {
            "type": "integer"
          },
          "per_page": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          },
          "total_pages": {
            "type": "integer"
          }
        }
      },
      "inline_response_201": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/subscription"
          },
          "status": {
            "type": "string",
            "example": "subscription created"
          }
        }
      },
      "inline_response_200_1": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "data": {
            "$ref": "#/components/schemas/inline_response_200_1_data"
          }
        }
      },
      "inline_response_200_2": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/subscription"
          },
          "status": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "businesses_data": {
        "type": "object",
        "properties": {
          "businesses": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/business"
            }
          }
        }
      },
      "inline_response_200_3": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": true
          },
          "data": {
            "$ref": "#/components/schemas/businesses_data"
          },
          "page": {
            "type": "integer"
          },
          "per_page": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          },
          "total_pages": {
            "type": "integer"
          }
        }
      },
      "businesses_body": {
        "type": "object",
        "properties": {
          "admin_account": {
            "$ref": "#/components/schemas/Staff"
          },
          "business": {
            "$ref": "#/components/schemas/business"
          },
          "meta": {
            "$ref": "#/components/schemas/businessMeta"
          }
        }
      },
      "inline_response_200_4": {
        "type": "object",
        "properties": {
          "status": {
            "type": "boolean",
            "example": true
          },
          "data": {
            "$ref": "#/components/schemas/inline_response_200_4_data"
          }
        }
      },
      "inline_response_200_5": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "OK"
          },
          "data": {
            "$ref": "#/components/schemas/inline_response_200_4_data"
          }
        }
      },
      "inline_response_200_data": {
        "type": "object",
        "properties": {
          "subscriptions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/subscription"
            }
          }
        }
      },
      "inline_response_200_1_data": {
        "type": "object",
        "properties": {
          "subscription": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/subscription"
            }
          },
          "page": {
            "type": "integer"
          },
          "per_page": {
            "type": "integer"
          },
          "total": {
            "type": "integer"
          },
          "total_pages": {
            "type": "integer"
          }
        }
      },
      "inline_response_200_4_data": {
        "type": "object",
        "properties": {
          "business": {
            "$ref": "#/components/schemas/business"
          }
        }
      }
    },
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}
